config/routes.rb
Rails.application.routes.draw do
  get 'posts/index'
  resources :posts
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/post.rb
class Post < ApplicationRecord
    validates :title, presence: true, length: { maximum: 20}
    validates :startday, presence: true 
    validates :finishday, presence: true
    validates :memo, length: { maximum: 500 }
    validate :start_finish_check
    def start_finish_check
        return false if finishday.blank? || startday.blank?
        if startday > finishday
            errors.add(:finishday, "は開始日より後の日付を選択してください")
        end
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  def index
    @posts = Post.all
    @schedule_total = Post.all.count
  end

  def new
    @post = Post.new
  end
  
  def create
    @post = Post.new(params.require(:post).permit(:user_id, :title, :startday, :finishday, :oneday, :memo)) 
    if @post.save
      flash[:notice] = "新規登録に成功しました"
      redirect_to :posts
    else
      flash[:notice] = "新規登録に失敗しました"
      render "new"
    end
  end

  def show
    @post = Post.find(params[:id])
  end

  def edit
    @post = Post.find(params[:id])
  end

  def update
    @post = Post.find(params[:id])
    if @post.update(params.require(:post).permit(:user_id, :title, :startday, :finishday, :oneday, :memo)) 
      flash[:notice] = "スケジュールを更新しました"
      redirect_to :posts
    else
      flash[:notice] = "スケジュールの更新に失敗しました"
      render "edit"
    end
  end

  def destroy
    @post = Post.find(params[:id])
     @post.destroy
     flash[:notice] = "ユーザーを削除しました"
     redirect_to :posts
  end
end
 

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Myapp15</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/posts/edit.html.erb
<h3>ユーザー編集</h3>
<% if flash[:notice] %>
<p class="notice"><%= flash[:notice] %></p>
<% end %>

<%= form_with model: @post do |f| %>
    <table>
      <tr>
          <th><%= f.label :user_id ,"名前" %></th>
          <td><%= f.text_field :user_id %></td>
      </tr>
  
      <tr>
          <th><%= f.label :title ,"タイトル" %></th>
          <td><%= f.text_field :title %></td>
      </tr>
  
      <tr>
          <th><%= f.label :startday ,"開始日" %></th>
          <td><%= f.date_field :startday %></td>
      </tr>
  
      <tr>
          <th><%= f.label :finishday ,"終了日" %></th>
          <td><%= f.date_field :finishday %></td>
      </tr>
  
      <tr>
          <th><%= f.label :oneday ,"終日" %></th>
          <td><%= f.check_box :oneday, {}, "true", "false" %><br>終日の場合はチェックを入れます</td>
      </tr>
      <tr>
          <th><%= f.label :memo ,"メモ欄" %></th>
          <td><%= f.text_area :memo %></td>
      </tr>
     
  
    </table>

  <div>
    <ul>
      <li><%= f.submit "編集を完了する" %></li>
      <li><%= link_to "ユーザー情報一覧に戻る", :posts %></li>
    </ul>
  </div>
<% end %>

app/views/posts/index.html.erb
<h3>ユーザー情報一覧</h3>
<% if flash[:notice] %>
<p class="notice"><%= flash[:notice] %></p>
<% end %>

<table>
  <thead>
    <tr>
      <th>名前</th>
      <th>タイトル</th>
      <th>開始日</th>
      <th>終了日</th>
      <th>終日</th>
      <th>更新日時</th>
      <th>詳細</th>
      <th>編集</th>
      <th>削除</th>
    </tr>
  </thead>

  <tbody>
    <% @posts.each do |post| %>
      <tr>
        <td><%= post.user_id %></td>
        <td><%= post.title %></td>
        <td><%= post.startday%></td>
        <td><%= post.finishday %></td>
        <td>
          <% if post.oneday == "true" %>
          <%= "⚪︎" %>
          <% else post.oneday == "false" %>
           <%= ""%>
           <% end %>
        </td>
        <td><%= post.updated_at.to_s(:datetime_jp) %></td>
        <td><%= link_to"詳細", post%></td>
        <td><%= link_to"編集", edit_post_path(post)%></td>
        <td><%= link_to "削除", post, method: :delete, data: { confirm: "本当に削除しますか？" } %></td>
      </tr>
    <% end %>
    <p><%= link_to "ユーザー新規登録", :new_post %></p>
  </tbody>
</table>

<div>
<p>予定の合計<%= @schedule_total %></p>
<p> 本日の日付 <%= Time.now.strftime("%Y/%m/%d")%></p>
</div>

app/views/posts/new.html.erb
<h3>ユーザー新規作成</h3>
<% if flash[:notice] %>
<p class="notice"><%= flash[:notice] %></p>
<% end %>

<%= form_with model: @post do |f| %>
  <table>
    <tr>
        <th><%= f.label :user_id ,"名前" %></th>
        <td><%= f.text_field :user_id %></td>
    </tr>

    <tr>
        <th><%= f.label :title ,"タイトル" %></th>
        <td><%= f.text_field :title %></td>
    </tr>

    <tr>
        <th><%= f.label :startday ,"開始日" %></th>
        <td><%= f.date_field :startday %></td>
    </tr>

    <tr>
        <th><%= f.label :finishday ,"終了日" %></th>
        <td><%= f.date_field :finishday %></td>
    </tr>

    <tr>
        <th><%= f.label :oneday ,"終日" %></th>
        <td><%= f.check_box :oneday, {}, "true", "false" %><br>終日の場合はチェックを入れます</td>
    </tr>
    <tr>
        <th><%= f.label :memo ,"メモ欄" %></th>
        <td><%= f.text_area :memo %></td>
    </tr>
   

  </table>

  <div>
    <ul>
      <li><%= f.submit "登録完了する"%></li>
      <li><%= link_to "ユーザー情報一覧に戻る", :posts %></li>
    </ul>
  </div>
<% end %>

app/views/posts/show.html.erb
<h3>ユーザー詳細</h3>
<table>
  <tr>
    <th>名前</th>
    <td><%= @post.user_id %></td>
  </tr>
  <tr>
    <th>タイトル</th>
    <td><%= @post.title %></td>
  </tr>
  <tr>
    <th>開始日</th>
    <td><%= @post.startday %></td>
  </tr>
  <tr>
    <th>終了日</th>
    <td><%= @post.finishday %></td>
  </tr>
  <tr>
    <th>終日</th>
    <td>
          <% if @post.oneday === 'true' %>
          ⚪︎
          <% else @post.oneday === 'false' %>
           <% end %>
        </td>
  </tr>
  <tr>
    <th>スケジュールメモ</th>
    <td><%= @post.memo %></td>
  </tr>
</table>

<div>
  <ul>
    <li><%= link_to "ユーザー情報一覧に戻る", :posts %></li>
  </ul>
</div>